apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golist-db
  namespace: argocd
spec:
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mariadb
    targetRevision: 11.1.0
    helm:
      values: |
        architecture: standalone
        auth:
          database: golist
          username: golist
          password: golist
        image:
          registry: docker.io
          repository: bitnami/mariadb
          tag: latest
  destination:
    namespace: golist
    server: https://kubernetes.default.svc
  project: golist
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
